services:
  swf-postgres:
    image: postgres:15-alpine
    container_name: swf-postgres
    environment:
      - POSTGRES_DB=ShitWithFriend
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=PasswordSegreta123!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - swf-net
    restart: always

  swf-api:
    container_name: swf-api
    # --- CAMBIAMENTO CRUCIALE ---
    # Ora scarichiamo l'immagine pronta dal tuo registro GitHub
    image: ghcr.io/pixelmaster93/swf.api:latest

    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__SWFDbConnectionString=Host=swf-postgres;Port=5432;Database=ShitWithFriend;Username=admin;Password=PasswordSegreta123!

      # Configurazione Auth
      - Authentication__Authority=http://keycloak-keycloak-1:8080/realms/ShitWithFriend
      - Authentication__Audience=swf-api
      - ASPNETCORE_Kestrel__Certificates__Default__AllowInvalid=true

      # Log impostato a Information per vedere le migrazioni
      - Logging__LogLevel__Microsoft.AspNetCore.Authentication=Information
      - Logging__LogLevel__Default=Information

    ports:
      - "5000:8080"
    # Il volume del codice sorgente non serve più, teniamo solo quello dei dati se l'app scrive file
    volumes:
      - ./swf_data:/app/data
    restart: always
    depends_on:
      - swf-postgres
    networks:
      - swf-net

networks:
  swf-net:
    external: true

volumes:
  postgres_data:
