// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShitWithFriendAPI.DBContext;

#nullable disable

namespace ShitWithFriendAPI.Migrations
{
    [DbContext(typeof(SWFContext))]
    [Migration("20260101133500_IncreaseStringLimits")]
    partial class IncreaseStringLimits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroupAdministrators", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupAdministrators");
                });

            modelBuilder.Entity("GroupUsers", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupUsers");
                });

            modelBuilder.Entity("ShitWithFriendAPI.Entities.Achievement", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XpValue")
                        .HasColumnType("integer");

                    b.HasKey("Code");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Code = "DEFAULT_1",
                            Description = "L'originale.",
                            IsSecret = false,
                            Name = "Classica",
                            XpValue = 0
                        },
                        new
                        {
                            Code = "DEFAULT_2",
                            Description = "Distinta ed elegante.",
                            IsSecret = false,
                            Name = "Il Signore",
                            XpValue = 0
                        },
                        new
                        {
                            Code = "DEFAULT_3",
                            Description = "Fatta con amore.",
                            IsSecret = false,
                            Name = "Love",
                            XpValue = 0
                        },
                        new
                        {
                            Code = "POOP_1",
                            Description = "La tua prima cacca registrata.",
                            IsSecret = false,
                            Name = "Il Primo Passo",
                            XpValue = 10
                        },
                        new
                        {
                            Code = "POOP_10",
                            Description = "10 cacche registrate.",
                            IsSecret = false,
                            Name = "Riscaldamento",
                            XpValue = 20
                        },
                        new
                        {
                            Code = "POOP_25",
                            Description = "25 cacche registrate.",
                            IsSecret = false,
                            Name = "Apprendista",
                            XpValue = 30
                        },
                        new
                        {
                            Code = "POOP_50",
                            Description = "50 cacche. Rispetto.",
                            IsSecret = false,
                            Name = "Cintura Marrone",
                            XpValue = 50
                        },
                        new
                        {
                            Code = "POOP_100",
                            Description = "100 cacche. Un esercito.",
                            IsSecret = false,
                            Name = "Il Centurione",
                            XpValue = 100
                        },
                        new
                        {
                            Code = "POOP_250",
                            Description = "250 cacche. Arte pura.",
                            IsSecret = false,
                            Name = "Maestro Zen",
                            XpValue = 250
                        },
                        new
                        {
                            Code = "POOP_500",
                            Description = "500 cacche. Regale.",
                            IsSecret = true,
                            Name = "Il Trono di Ceramica",
                            XpValue = 500
                        },
                        new
                        {
                            Code = "POOP_1000",
                            Description = "1000 cacche. Leggendario.",
                            IsSecret = true,
                            Name = "Divinità Intestinale",
                            XpValue = 1000
                        },
                        new
                        {
                            Code = "EARLY_BIRD",
                            Description = "Posta tra le 05:00 e le 07:00.",
                            IsSecret = false,
                            Name = "Il Gallo",
                            XpValue = 20
                        },
                        new
                        {
                            Code = "LUNCH_TIMER",
                            Description = "Posta tra le 12:30 e le 14:00.",
                            IsSecret = false,
                            Name = "Pausa Pranzo",
                            XpValue = 15
                        },
                        new
                        {
                            Code = "NIGHT_OWL",
                            Description = "Posta tra le 03:00 e le 05:00.",
                            IsSecret = true,
                            Name = "Il Vampiro",
                            XpValue = 50
                        },
                        new
                        {
                            Code = "WEEKEND_WARRIOR",
                            Description = "Cacca sia Sabato che Domenica nello stesso weekend.",
                            IsSecret = false,
                            Name = "Guerriero del Weekend",
                            XpValue = 30
                        },
                        new
                        {
                            Code = "NEW_YEAR",
                            Description = "Posta il 1° Gennaio.",
                            IsSecret = false,
                            Name = "Anno Nuovo",
                            XpValue = 50
                        },
                        new
                        {
                            Code = "VALENTINE",
                            Description = "Posta il 14 Febbraio.",
                            IsSecret = false,
                            Name = "Innamorato",
                            XpValue = 20
                        },
                        new
                        {
                            Code = "FERRAGOSTO",
                            Description = "Posta il 15 Agosto.",
                            IsSecret = false,
                            Name = "Cacca Caliente",
                            XpValue = 20
                        },
                        new
                        {
                            Code = "HALLOWEEN",
                            Description = "Posta il 31 Ottobre.",
                            IsSecret = true,
                            Name = "Terrore in Bagno",
                            XpValue = 30
                        },
                        new
                        {
                            Code = "XMAS",
                            Description = "Posta il 25 Dicembre.",
                            IsSecret = true,
                            Name = "Regalino di Natale",
                            XpValue = 50
                        },
                        new
                        {
                            Code = "STREAK_3",
                            Description = "3 giorni consecutivi.",
                            IsSecret = false,
                            Name = "Tris",
                            XpValue = 20
                        },
                        new
                        {
                            Code = "STREAK_7",
                            Description = "7 giorni consecutivi.",
                            IsSecret = false,
                            Name = "Settimana Santa",
                            XpValue = 50
                        },
                        new
                        {
                            Code = "STREAK_30",
                            Description = "30 giorni consecutivi.",
                            IsSecret = true,
                            Name = "Iron Man",
                            XpValue = 150
                        },
                        new
                        {
                            Code = "GAMER_ROOKIE",
                            Description = "Gioca la tua prima partita.",
                            IsSecret = false,
                            Name = "Insert Coin",
                            XpValue = 10
                        },
                        new
                        {
                            Code = "GAMER_COMPLETIONIST",
                            Description = "Gioca a tutti i minigiochi.",
                            IsSecret = false,
                            Name = "Nerd da Bagno",
                            XpValue = 100
                        },
                        new
                        {
                            Code = "KING_MONTH",
                            Description = "Vinci un titolo di Re del Mese.",
                            IsSecret = false,
                            Name = "Barone del Trono",
                            XpValue = 100
                        },
                        new
                        {
                            Code = "KING_YEAR",
                            Description = "Vinci un titolo di Re dell'Anno.",
                            IsSecret = false,
                            Name = "Imperatore Supremo",
                            XpValue = 500
                        },
                        new
                        {
                            Code = "TURBO_POOPER",
                            Description = "2 cacche in meno di 1 ora.",
                            IsSecret = true,
                            Name = "Mitragliatrice",
                            XpValue = 50
                        },
                        new
                        {
                            Code = "TYPE_LIQUID",
                            Description = "5 cacche di tipo Liquida.",
                            IsSecret = false,
                            Name = "Idrante",
                            XpValue = 30
                        });
                });

            modelBuilder.Entity("ShitWithFriendAPI.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("ShitWithFriendAPI.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MonthPoopKing")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("YearPoopKing")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MonthPoopKing");

                    b.HasIndex("YearPoopKing");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("ShitWithFriendAPI.Entities.HighScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("HighScores");
                });

            modelBuilder.Entity("ShitWithFriendAPI.Entities.Poop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TypeOfPoop")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Poops");
                });

            modelBuilder.Entity("ShitWithFriendAPI.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShitWithFriendAPI.Entities.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AchievementCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AchievementCode");

                    b.HasIndex("UserId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("ShitWithFriendAPI.Entities.UserGroupEmoji", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersGroupsEmoji");
                });

            modelBuilder.Entity("GroupAdministrators", b =>
                {
                    b.HasOne("ShitWithFriendAPI.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShitWithFriendAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupUsers", b =>
                {
                    b.HasOne("ShitWithFriendAPI.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShitWithFriendAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShitWithFriendAPI.Entities.Group", b =>
                {
                    b.HasOne("ShitWithFriendAPI.Entities.User", "MonthPoopKingUser")
                        .WithMany()
                        .HasForeignKey("MonthPoopKing")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShitWithFriendAPI.Entities.User", "YearPoopKingUser")
                        .WithMany()
                        .HasForeignKey("YearPoopKing")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MonthPoopKingUser");

                    b.Navigation("YearPoopKingUser");
                });

            modelBuilder.Entity("ShitWithFriendAPI.Entities.HighScore", b =>
                {
                    b.HasOne("ShitWithFriendAPI.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShitWithFriendAPI.Entities.User", "User")
                        .WithMany("Highscores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShitWithFriendAPI.Entities.Poop", b =>
                {
                    b.HasOne("ShitWithFriendAPI.Entities.User", "User")
                        .WithMany("Poops")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShitWithFriendAPI.Entities.UserAchievement", b =>
                {
                    b.HasOne("ShitWithFriendAPI.Entities.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShitWithFriendAPI.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShitWithFriendAPI.Entities.UserGroupEmoji", b =>
                {
                    b.HasOne("ShitWithFriendAPI.Entities.Group", "Group")
                        .WithMany("UserGroupEmojis")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShitWithFriendAPI.Entities.User", "User")
                        .WithMany("UserGroupEmojis")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShitWithFriendAPI.Entities.Group", b =>
                {
                    b.Navigation("UserGroupEmojis");
                });

            modelBuilder.Entity("ShitWithFriendAPI.Entities.User", b =>
                {
                    b.Navigation("Highscores");

                    b.Navigation("Poops");

                    b.Navigation("UserGroupEmojis");
                });
#pragma warning restore 612, 618
        }
    }
}
